spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vuetest?characterEncoding=utf8&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
server:
  port: 9999

com:
  seele:
    name: 123
    age: 66

mybatis:
  mapper-locations: classpath:mapper/*.xml
